version: '2'
services:
  beehiveai-collector:
    volumes:
      - .:/code
    build: .
    environment:
      - BEEHIVEAI_CHECK_INTERVAL=-1
      - BHIVE_API_TOKEN=''
    volumes:
      - ~/.aws:/root/.aws